config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search"
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :messages, only: [:show, :create]

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    get 'new/mail' => 'groups#new_mail'
    get 'send/mail' => 'groups#send_mail'
  end
  get 'search', to: 'searches#search'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    if @group.owner_id == current_user.id
      render 'edit'
    else
      redirect_to groups_path
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:group_id])
    unless @group.users.include?(current_user)
      @group.users << current_user
    end
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Group</h2>
      <div class="text-danger">
      <% if @group.errors.any? %>
        <h3><%= pluralize(@group.errors.count,"error") %> prohibited this obj from being saved:</h3>
        <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      </div>

      <%= form_with model: @group, local: true do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.attachment_field :image, class:"form-control-file" %>
        </div>
        <%= f.submit "Editind Group", class:"btn btn-sm btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
       <%= render 'users/list', user:current_user %>
       <%= render 'books/new_book', book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
          <tr>
            <td><%= attachment_image_tag group, :image, :fill,40,40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
            <td><%= link_to group.name, group_path(group) %></td>
            <td><%= group.introduction %></td>
            <td><%= group.users.count %></td>
            <td>
              <% if group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(group), class:"btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Create Group</h2>
      <div class="text-danger">
      <% if @group.errors.any? %>
        <h3><%= pluralize(@group.errors.count,"error") %> prohibited this obj from being saved:</h3>
        <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      </div>

      <%= form_with model: @group, local: true do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.attachment_field :image, class:"form-control-file" %>
        </div>
        <%= f.submit "Creat Group", class:"btn btn-sm btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url: group_send_mail_path(@group), method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.label :Title %>
          <%= f.text_field :mail_title, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Content %>
          <%= f.text_area :mail_content, class:"form-control" %>
        </div>
        <%= f.submit '送信', class:"btn btn-sm btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>送信が完了しました</h2>
      <div class="mt-4">
        <p>内容は以下の通りです。</p>
        <div>
          [タイトル]
          <p class="font-weight-bold"><%= @mail_title %></p>
        </div>
        <div>
          [本文]
          <p class="font-weight-bold"><%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
       <%= render'users/list',user:current_user %>
       <%= render'books/new_book',book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= attachment_image_tag @group, :image, :fill,40,40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
                <%= user.name %><br />
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(@group), class:"btn btn-sm btn-success" %>
                <%= link_to 'Notice an Event', group_new_mail_path(@group), class:"btn btn-sm btn-primary" %>
              <% elsif @group.users.include?(current_user) %>
                <%= link_to 'Leave this group', group_path(@group), method: :delete, class:"btn btn-sm btn-danger" %>
              <% else %>
                <%= link_to 'Join this group', group_join_path(@group), class:"btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>