config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search"
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :messages, only: [:show, :create]

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    get 'new/mail' => 'groups#new_mail'
    get 'send/mail' => 'groups#send_mail'
  end
  get 'search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  is_impressionable counter_cache: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.last_week
    Book.joins(:favorites).where(favorites: { created_at: 6.days.ago.beginning_of_day..Time.current}).group(:book_id).order("count(*) desc")
  end
  scope :latest, -> { order(id: :desc) }
  scope :rated, -> { order(rate: :desc) }
  scope :views, -> { order(impressions_count: :desc) }
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.days.ago.beginning_of_day..Time.zone.now) }
  scope :created_last_week, -> { where(created_at: 13.days.ago.beginning_of_day..7.days.ago.end_of_day) }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, foreign_key: 'user_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(follow_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    if params[:sort] == 'latest'
      @books = Book.latest
    elsif params[:sort] == 'rated'
      @books = Book.rated
    elsif params[:sort] == 'favorite'
      @books = Book.last_week
    elsif params[:sort] == 'views'
      @books = Book.views
    else
      @books = Book.all
    end
    @chartbooks = Book.all
    @books_by_day = @chartbooks.group_by_day(:created_at, last: 7).size
    @chartlabels = @books_by_day.map(&:first).to_json.html_safe
    @chartdatas = @books_by_day.map(&:second)
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @book_comment = BookComment.new
    @user = User.find(@book.user_id)
    impressionist(@book, nil, unique: [:ip_address])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), flash: { notice: "You have created book successfully." }
    else
      session[:error_message] = @book.errors.full_messages
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(params[:id]), flash: { notice: "You have updated book successfully." }
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @today_books = @books.created_today
    @yesterday_books = @books.created_yesterday
    @day_ratio = @today_books.count / @yesterday_books.count.to_f
    @this_week_books = @books.created_this_week
    @last_week_books = @books.created_last_week
    @week_ratio = @this_week_books.count / @last_week_books.count.to_f
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を入力してください"
    else
      created_at = params[:created_at]
      @search_book = @books.where('created_at LIKE ?', "#{created_at}%").count
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(params[:id]), flash: { notice: "You have updated user successfully." }
    else
      render "edit"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_chart.html.erb
<canvas id="myChart" width="550" height="300"> </canvas>

<script>
  var ctx = document.getElementById("myChart").getContext('2d');
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: <%= @chartlabels %>,
      datasets: [{
        label: "投稿した本の数",
        data: <%= @chartdatas %>,
        backgroundColor: 'rgba(0, 0, 0, 0)',
        borderColor: 'rgba(20, 20, 200, 1.0)',
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 10,
            suggestedMin: 0,
            stepSize: 1
          }
        }]
      },
    }
  });
</script>

app/views/books/_new_book.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book,local:true do |f|  %>
  <div class="form-group">
    <%= f.label :Title %>
    <%= f.text_field :title, class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :Opinion %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Category %>
    <%= f.text_field :category, class:"form-control" %>
  </div>
  <div class="form-group" id="star">
    <%= f.label :rate %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <script>
    $('#star').raty({
      size: 36,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[rate]',
      half: true,
    });
  </script>
  <%= f.submit  class: 'btn btn-success mt-3' %>
<% end %>

app/views/books/_newbook.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book,local:true do |f|  %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class:"form-control"%>
  </div>
  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <label>Category</label>
    <%= f.text_field :category, class:"form-control" %>
  </div>
  <div class="form-group" id="star">
    <label>rate</label>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <script>
    $('#star').raty({
      size: 36,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[rate]',
      half: true,
    });
  </script>
  <%= f.submit  class: 'btn btn-success mt-3' %>
<% end %>

app/views/books/_ratio_table.html.erb
<h2>投稿の前日比・前週比</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今日の投稿数</th>
        <th>前日の投稿数</th>
        <th>前日比</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @today_books.count %></td>
      <td><%= @yesterday_books.count %></td>
      <td>
        <% begin %>
          <%= (@day_ratio * 100).round.to_s + '%' %>
        <% rescue %>
          <%= 0.to_s + '%' %>
        <% end %>
      </td>
    </tbody>
  </table>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今週の投稿数</th>
        <th>前週の投稿数</th>
        <th>前週比</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @this_week_books.count %></td>
      <td><%= @last_week_books.count %></td>
      <td>
        <% begin %>
          <%= (@week_ratio * 100 ).round.to_s + '%' %>
        <% rescue %>
          <%= 0.to_s + '%' %>
        <% end %>
      </td>
    </tbody>
  </table>

app/views/books/_star.html.erb
<script>
  $('#star-rate-<%= book.id %>').raty({
    size: 36,
    starOff: '<%= asset_path('star-off.png') %>',
    starOn: '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= book.rate %>,
  });
</script>

app/views/books/_weekly_post.html.erb
<h2>7日間分の投稿数</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>6日前</th>
        <th>5日前</th>
        <th>4日前</th>
        <th>3日前</th>
        <th>2日前</th>
        <th>1日前</th>
        <th>今日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @chartdatas.each do |chartdatas| %>
          <td><%= chartdatas %></td>
        <% end %>
      </tr>
    </tbody>
  </table>

app/views/books/edit.html.erb
<div class="container">
  <% breadcrumb :book_edit, @book %>
  <div class="row">
    <div class="col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div class="text-danger">
        <% if @book.errors.any? %>
          <h3><%= pluralize(@book.errors.count,"error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
       <%= form_with model:@book,local:true do |f| %>
        <div class="form-group">
          <%= f.label :Title %>
          <%= f.text_field :title, class:"form-control mb-3" %>
        <div class="form-group">
          <%= f.label :Opinion %>
          <%= f.text_area :body, class:"form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label :Category %>
          <%= f.text_field :category, class:"form-control" %>
        </div>
        <div class="mb-3" id="star-rate-<%= @book.id %>">
          <%= render'books/star', book:@book %>
        </div>
        <%= f.submit "Update Book", class: 'btn btn-success' %>
      <% end %>
      <div class="d-flex flex-row mt-3">
        <%= link_to "Show", book_path(@book) %>
        <p class="mx-1">|</p>
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <% breadcrumb :books_index %>
  <% object = session[:error_message] %>
  <% if !object.nil? %>
    <div class="text-danger">
      <h2><%= pluralize(object.count, "error") %> prohibited this obj from being saved:</h2>
      <ul>
      <% object.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% session[:error_message] = nil %>
  <div class="row">
    <div class="col-md-3">
      <%= render'users/list',user:@user %>
      <%= render'books/new_book',book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(sort: 'latest') %> |
      <%= link_to '評価の高い順', books_path(sort: 'rated') %> |
      <%= link_to '週間いいねランキング', books_path(sort: 'favorite') %> |
      <%= link_to '閲覧数が多い順', books_path(sort: 'views') %>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" , size:'40x40'%>
              <% end %>
            </td>
            <td class="col-2">
              <%= link_to book.title, book_path(book) %>
            </td>
            <td class="col-2">
              <%= book.body %>
            </td>
            <td class="col-1">
              <%= link_to book.category, search_path(:model => "category", :method =>"perfect", :content => book.category)  %>
            </td>
            <td  id="favorite_buttons_<%= book.id %>">
              <%= render 'favorites/favorite', book:book %>
            </td>
            <td class="col-3">
              コメント数: <%= book.book_comments.count %><br />
              閲覧数: <%= book.impressions_count %>
            </td>
            <td class="col-4" id="star-rate-<%= book.id %>">
              <%= render 'books/star', book:book %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'books/weekly_post' %>
      <%= render 'books/chart' %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <% breadcrumb :book_show, @book %>
  <p class="notice text-success m-0"><%= notice %></p>
  <div class="row">
    <div class="col-md-3">
      <%= render'users/list',user:@user %>
      <%= render'books/new_book',book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" , size:'40x40'%><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td><%= @book.body %></td>
            <td>
              <%= link_to @book.category, search_path(:model => "category", :method =>"perfect", :content => @book.category) %>
            </td>
            <td id="favorite_buttons_<%= @book.id %>">
              <%= render "favorites/favorite", book:@book %>
            </td>
            <td id="comment_count_<% @book.id %>">
              コメント数: <%= @book.book_comments.count %><br />
              閲覧数: <%= @book.impressions_count %>
            </td>
            <td id="star-rate-<%= @book.id %>">
              <%= render'books/star', book:@book %>
            </td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success' %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-danger' %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div id='comment_index'><%= render "book_comments/comment", book:@book %></div>
      <div>
        <%= form_with model:[@book,@book_comment] do |f| %>
          <%= f.text_area :comment, class:"form-control" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_chat.html.erb
<% unless user.id == current_user.id %>
  <% if (current_user.following? user) && (user.following? current_user)  %>
    <%= link_to 'チャットへ', message_path(user.id) %>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  <% end %>
<% end %>

app/views/users/_list.html.erb
<h2>User info</h2>
<div>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
</div>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>inroduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <td>
      <%= link_to user.followings.count, user_followings_path(user) %>
    </td>
  </tr>
  <tr>
    <th>followers</th>
    <td>
      <%= link_to user.followers.count, user_followers_path(user) %>
    </td>
  </tr>
</table>

<% if user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-dark btn-sm btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
<% else %>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn btn-primary" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
  <% end %>
<% end %>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <% breadcrumb :user_edit, @user %>
    <div class="col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div class="text-danger">
        <% if @user.errors.any? %>
          <h3><%= pluralize(@user.errors.count,"error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, id:"inputName", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %><br />
          <%= f.attachment_field :profile_image, placeholder:"プロフィール画像" %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <%= f.submit "Update User", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <% breadcrumb :users_index %>
    <div class="col-md-3">
      <%= render'users/list', user:current_user %>
      <%= render'books/new_book', book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to 'グループを作成する', new_group_path %> |
      <%= link_to 'グループ一覧', groups_path %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
            </td>
            <td class="col-2"><%= user.name %></td>
            <td class="col-3">
              フォロー数: <%= user.followings.count %>
            </td>
            <td class="col-3">
              フォロワー数: <%= user.followers.count %>
            </td>
            <td class="col-3">
              <%= render'users/follow', user:user %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#result').html(" <%= j(render'users/search', search_book:@search_book) %> ");

app/views/users/show.html.erb
<p class="notice text-success m-0"><%= notice %></p>
<div class="container">
  <div class="row">
    <% breadcrumb :user_show, @user %>
    <div class="col-md-3">
      <%= render 'users/list', user:@user %>
      <%= render 'users/chat', user:@user %>
      <%= render 'books/new_book', book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" , size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td>
              <%= link_to search_path(:model => "category", :method =>"perfect", :content => book.category) do %>
                <%= book.category %>
              <% end %>
            </td>
            <td id="favorite_buttons_<%= book.id %>">
              <%= render "favorites/favorite", book:book %>
            </td>
            <td>
              コメント数: <%= book.book_comments.count %><br />
              閲覧数: <%= book.impressions_count %>
            </td>
            <td id="star-rate-<%= book.id %>">
              <%= render 'books/star', book:book %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%= form_with url: user_search_path(@user), method: :get do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class:'btn btn-primary' %>
      <% end %>
      <div id="result">
        <% if @search_book.present? %>
          <%= render 'users/search', search_book:@search_book %>
        <% end %>
      </div>
      <%= render 'books/ratio_table' %>
    </div>
  </div>
</div>