config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => "users#search"
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :messages, only: [:show, :create]

  resources :groups do
    get 'join' => 'groups#join', as: 'join'
    get 'new/mail' => 'groups#new_mail'
    get 'send/mail' => 'groups#send_mail'
  end
  get 'search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  is_impressionable counter_cache: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.last_week
    Book.joins(:favorites).where(favorites: { created_at: 6.days.ago.beginning_of_day..Time.current}).group(:book_id).order("count(*) desc")
  end
  scope :latest, -> { order(id: :desc) }
  scope :rated, -> { order(rate: :desc) }
  scope :views, -> { order(impressions_count: :desc) }
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.days.ago.beginning_of_day..Time.zone.now) }
  scope :created_last_week, -> { where(created_at: 13.days.ago.beginning_of_day..7.days.ago.end_of_day) }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, foreign_key: 'user_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(follow_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    if params[:sort] == 'latest'
      @books = Book.latest
    elsif params[:sort] == 'rated'
      @books = Book.rated
    elsif params[:sort] == 'favorite'
      @books = Book.last_week
    elsif params[:sort] == 'views'
      @books = Book.views
    else
      @books = Book.all
    end
    @chartbooks = Book.all
    @books_by_day = @chartbooks.group_by_day(:created_at, last: 7).size
    @chartlabels = @books_by_day.map(&:first).to_json.html_safe
    @chartdatas = @books_by_day.map(&:second)
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @book_comment = BookComment.new
    @user = User.find(@book.user_id)
    impressionist(@book, nil, unique: [:ip_address])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), flash: { notice: "You have created book successfully." }
    else
      session[:error_message] = @book.errors.full_messages
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(params[:id]), flash: { notice: "You have updated book successfully." }
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/f8d37013c4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-1 ">
        <div class="container">
          <a class="navbar-brand p-2" href="#">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto ">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class:'nav-link text-light' do%>
                  <i class="fas fa-home"> Home</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path,class:'nav-link text-light' do %>
                  <i class="fas fa-users"> Users</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path,class:'nav-link text-light' do %>
                  <i class="fas fa-book-open"> Books</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path,method: :delete,class:'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"> logout</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= render 'searches/form' %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to root_path,class:'nav-link text-light' do %>
                  <i class="fas fa-home"> Home</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path,class:'nav-link text-light' do %>
                  <i class="fas fa-link"> About</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path,class:'nav-link text-light' do %>
                  <i class="fas fa-user-plus"> sign up</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class:'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"> login</i>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mt-2">
    <%= breadcrumbs separator: "&rsaquo;", class:"ml-5" %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.Inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>